#%RAML 1.0
title: Hello
mediaType: application/json
types:
  Repository:
    properties:
      id: integer
      name: string
      lastName: string

/repositories:
  get:
   responses:
     200:
      body: Repository[]