#%RAML 1.0
title: Hello
uses:
 s: shapes.raml
mediaType: application/json
types:
  Repository:
    properties:
      id: integer
      name: string
      lastName: string
  RepositoryData:
     (s.shapeOf): Repository
     properties:
       id: integer
       name: string
/repositories:
  get:
   responses:
     200:
      body: RepositoryData[]
  post:
    body: Repository